services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: donation_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-donation_db}
      POSTGRES_USER: ${POSTGRES_USER:-donation_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-donation_pass}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - donation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-donation_user} -d ${POSTGRES_DB:-donation_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: 
      context: ./donation-platfrom-backend
      dockerfile: Dockerfile
    container_name: donation_backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-donation_user}:${POSTGRES_PASSWORD:-donation_pass}@postgres:5432/${POSTGRES_DB:-donation_db}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      API_V1_STR: ${API_V1_STR:-/api/v1}
      PROJECT_NAME: ${PROJECT_NAME:-Donation Platform}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      SMTP_SERVER: ${SMTP_SERVER:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      FROM_EMAIL: ${FROM_EMAIL:-noreply@qalbwahed.org}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      ENVIRONMENT: ${ENVIRONMENT:-production}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./donation-platfrom-backend/uploads:/app/uploads
    networks:
      - donation_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./donation-platform-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
        VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY:-${STRIPE_PUBLISHABLE_KEY}}
        VITE_ENVIRONMENT: ${VITE_ENVIRONMENT:-production}
    container_name: donation_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - donation_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  donation_network:
    driver: bridge
