"""add_language_field_to_newsletter_subscriptions

Revision ID: 94fbce5e8568
Revises: d6aa88d8dd4b
Create Date: 2025-06-22 15:53:48.817773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fbce5e8568'
down_revision: Union[str, None] = 'd6aa88d8dd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_subscriptions', sa.Column('language', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter_subscriptions', 'language')
    # ### end Alembic commands ###
