"""Add markdown_text field and rename image_url to image_path

Revision ID: e7eb99ba738a
Revises: 
Create Date: 2025-06-04 21:54:47.551751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7eb99ba738a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('markdown_text', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.drop_column('campaigns', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('campaigns', 'image_path')
    op.drop_column('campaigns', 'markdown_text')
    # ### end Alembic commands ###
